name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - clang-tidy-check
      - conda-cpp-build
      - conda-cpp-tests
      - conda-python-build
      - docs-build
      - conda-python-tests
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-builder.yaml@branch-23.06
  checks:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/checks.yaml@branch-23.06
  clang-tidy-check:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@branch-23.06
    with:
      build_type: pull-request
      arch: "amd64"
      container_image: "rapidsai/ci:latest"
      run_script: "ci/test_clang_tidy.sh"
  conda-cpp-build:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-cpp-build.yaml@branch-23.06
    with:
      build_type: pull-request
      build_script: ci/build_cpp.sh
  conda-cpp-tests:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-cpp-tests.yaml@branch-23.06
    with:
      build_type: pull-request
      test_script: ci/test_cpp.sh
  conda-python-build:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-build.yaml@branch-23.06
    with:
      build_type: pull-request
      build_script: ci/build_python.sh
  conda-python-tests:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/conda-python-tests.yaml@branch-23.06
    with:
      build_type: pull-request
      test_script: ci/test_python.sh
  docs-build:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/custom-job.yaml@branch-23.06
    with:
      build_type: pull-request
      arch: "amd64"
      container_image: "rapidsai/ci:latest"
      run_script: "ci/build_docs.sh"
